name: Download APKs
description: 'Download APK from APKMirror'
inputs:
    org:
      description: 'Organization name'
      required: true
    repo:
      description: 'Repository name'
      required: true
    version:
      description: 'Specific version to download (optional, auto-detects latest if not provided)'
      required: false
    versionPattern:
      description: 'Regex pattern to match version (e.g., ".*-pixel" or ".*-gphone")'
      required: false
    includePrerelease:
      description: 'Include alpha/beta versions when auto-detecting'
      required: false
      default: 'false'
    bundle:
      description: 'Download app bundle (AAB) instead of APK'
      required: false
      default: 'false'
    filename:
      description: 'Output filename (uses server filename if not specified)'
      required: false
    overwrite:
      description: 'Overwrite existing file'
      required: false
      default: 'true'

outputs:
  filename:
    description: 'The downloaded filename'

runs:
  using: 'node20'
  main: 'dist/index.js'